adding system.reative.linq clears this error
compiling in visual studio 2019 .net 4.8 throws

Severity Code Description Project File Line Suppression State
Error CS1660 Cannot convert lambda expression to type 'IObserver<(ModelInterfaceExtenders extenders, Type targetInterface)>' because it is not a delegate type Xpand.ExpressApp.XtraDashboard.Win C:\s11\coach\X\Xpand\Xpand.ExpressApp.Modules\XtraDashboard.Win\DashboardWindowsFormsModule.cs 37 Active


please refer to this link 

https://stackoverflow.com/questions/9454030/error-cannot-convert-lambda-expression-in-subscribe-for-an-iobservablepoint/9591210